server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8888

internal:
  api:
    key: ${INTERNAL_API_KEY:docker-dev-key}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
