internal:
  api:
    key: local-dev-key

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ms-learning

server:
  port: 8083
aws:
  region: us-east-1
  endpoint-override: http://localhost:4566
  access-key: test
  secret-key: test
  dynamodb:
    table-name: users
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
