server:
  port: 8083

aws:
  region: us-east-1
  endpoint-override: http://localstack:4566
  access-key: test
  secret-key: test
  dynamodb:
    table-name: users

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    config:
      uri: http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
