server:
  port: ${PORT:8083}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
aws:
  region: ${AWS_REGION:us-east-1}
  endpoint-override: ""
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  dynamodb:
    table-name: ${USERS_TABLE:users}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
