spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      uri: http://config-server:8888

services:
  user-service-url: http://user-service:8083
  payment-service-url: http://payment-service:8082

internal:
  api:
    key: ${INTERNAL_API_KEY:docker-dev-key}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
