spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ms-learning

internal:
  api:
    key: local-dev-key

services:
  user-service-url: http://localhost:8083
  payment-service-url: http://localhost:8082

management:
  endpoint:
    health:
      show-details: always
