spring:
  config:
    import: "aws-parameterstore:/ms-learning/"
  datasource:
    url: ${/ms-learning/order/db-url}
    username: ${/ms-learning/order/db-username}
    password: ${/ms-learning/order/db-password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate

services:
  user-service-url: ${/ms-learning/user/url}
  payment-service-url: ${/ms-learning/payment/url}
  saga-state-machine-arn: ${/ms-learning/order/saga-state-machine-arn}
  internal-api-key: ${/ms-learning/order/internal-api-key}

aws:
  region: us-east-1

management:
  endpoint:
    health:
      show-details: when-authorized
