spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

services:
  user-service-url: http://user-service:8083
  payment-service-url: http://payment-service:8082

management:
  endpoint:
    health:
      show-details: always
