spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

services:
  user-service-url: http://localhost:8083
  payment-service-url: http://localhost:8082

management:
  endpoint:
    health:
      show-details: always
