spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

services:
  user-service-url: http://localhost:8083
  payment-service-url: http://localhost:8082
  saga-state-machine-arn: arn:aws:states:us-east-1:000000000000:stateMachine:local-order-saga
  internal-api-key: internal-secret

aws:
  sfn-endpoint: http://localhost:4566

management:
  endpoint:
    health:
      show-details: always
