spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: paymentApproved;paymentFailed
    stream:
      bindings:
        order-events-out-0:
          destination: order.events
        paymentApproved-in-0:
          destination: payment.events
          group: order-service-approved
        paymentFailed-in-0:
          destination: payment.events
          group: order-service-failed
      rabbit:
        bindings:
          order-events-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: headers['routingKey']
          paymentApproved-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: payment.approved
              auto-bind-dlq: true
              dead-letter-queue-name: payment.events.dlq
          paymentFailed-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: payment.failed
              auto-bind-dlq: true
              dead-letter-queue-name: payment.events.dlq

services:
  user-service-url: ${USER_SERVICE_URL}
  payment-service-url: ${PAYMENT_SERVICE_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoint:
    health:
      show-details: when-authorized
