apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-service.serviceAccountName" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  {{- with .Values.irsa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
